services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: captchamaster-api
    restart: unless-stopped
    ports:
      - '8888:8888'
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      PORT: 8888
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET}
      AUTH_FINGERPRINT_SECRET: ${AUTH_FINGERPRINT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CRYPTOMUS_API_KEY: ${CRYPTOMUS_API_KEY}
      CRYPTOMUS_MERCHANT_ID: ${CRYPTOMUS_MERCHANT_ID}
    volumes:
      - api_uploads:/app/uploads
      - api_logs:/app/logs

volumes:
  api_uploads:
  api_logs:
